'Computer Vision':
    'Computer Vision': '"cs.CV" ANDNOT "Masked Autoencoder"'

'NLP':
    'NLP': '"cs.CL" ANDNOT "Prompt Tuning" ANDNOT "Sentence Embedding"'
    'Prompt Tuning': '"cs.AI" AND "Prompt Tuning"'
    'Sentence Embedding': '"cs.AI" AND "Sentence Embedding"'

'Unsupervised Learning':
    'Contrastive Learning': '"cs.AI" AND "Contrastive Learning"'
    'Clustering': '"cs.AI" AND "Clustering"'

"Reinforcement Learning":
    "Reinforcement Learning": '"Reinforcement Learning" OR "RL"'

"Continual Learning":
    "Continual Learning": '"Continual Learning" OR "Lifelong Learning"'

