name: Clean paper list

on:
  schedule:
    - cron: "0 0 */90 * *"
  push:
    branches:
      - main
    paths:
      - 'core/clean.py'
      - '/.github/workflows/clean.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run clean.py
        run: python ./core/clean.py
        
      - name: Set up git user
        uses: fregante/setup-git-user@v1
      
      - name: Update daily arxiv
        run: |
          git add ./assets
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m ":memo: Clean paper list ($(date '+%m-%d'))";
            git push origin main;
          else
            echo "no changes";
          fi
          
      


      
      
