name: Push Daily ArXiv

on:
  schedule:
    - cron: "43 10 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Shanghai"
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run core module
        run: python ./core/main.py
        
      - name: Set up git user
        uses: fregante/setup-git-user@v1
      
      - name: Update daily arxiv
        run: |
          git add ./assets
          git commit -m ":memo: Update daily arxiv ($(date '+%m-%d'))"
          git push origin main
      


      
      
